// @ember/connectors rebuilt — edit this file to force tsx watch to reload packaged dependencies.
import Fastify from "fastify";
import cors from "@fastify/cors";
import {
  executeProviderChat,
  getConnectorModelCatalog,
  launchProviderConnect,
  providerCanChat,
  recheckProvider,
  streamProviderChat,
} from "@ember/connectors";
import {
  type ConnectorTypeId,
  ensureDataFiles,
  getProviderCapabilities,
  readConnectorTypes,
  readConversations,
  readProviderSecrets,
  readProviders,
  readRoleAssignments,
  readRuntime,
  readSettings,
  writeConversations,
  writeProviderSecrets,
  writeProviders,
  writeRoleAssignments,
  writeSettings,
} from "@ember/core";
import type {
  ChatExecutionResult,
  ChatMessage,
  ChatMode,
  ChatRequest,
  ChatStreamEvent,
  Conversation,
  ConversationSummary,
  Provider,
  Role,
  RoleAssignment,
} from "@ember/core";
import type { UiBlock } from "@ember/ui-schema";
import { getPromptStack } from "@ember/prompts";
import {
  buildDispatchInput,
  formatRouteSource,
  resolveDispatchDecision,
  routeAutoRequestPolicy,
  type AutoRouteDecision,
} from "./routing.js";
import { createToolHandler, getToolsForRole, getToolSystemPrompt, setToolConfig } from "./tools/index.js";

const host = process.env.EMBER_RUNTIME_HOST ?? "0.0.0.0";
const port = Number(process.env.EMBER_RUNTIME_PORT ?? "3005");

function createId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function requestHasImageAttachments(request: ChatRequest): boolean {
  return request.conversation.some((message) =>
    (message.attachments ?? []).some((attachment) => attachment.kind === "image"),
  );
}

function summarizeText(content: string, limit = 84): string {
  const normalized = content.replace(/\s+/g, " ").trim();
  if (!normalized) {
    return "Untitled chat";
  }

  return normalized.length > limit ? `${normalized.slice(0, limit - 1)}…` : normalized;
}

function sanitizeRecord(value: Record<string, string> | undefined): Record<string, string> {
  if (!value) {
    return {};
  }

  return Object.fromEntries(
    Object.entries(value)
      .map(([key, item]) => [key, item.trim()] as const)
      .filter(([, item]) => item.length > 0),
  );
}

function toConversationSummary(conversation: Conversation): ConversationSummary {
  const { messages: _messages, ...summary } = conversation;
  return summary;
}

function normalizeChatMode(mode: ChatMode): ChatMode {
  return mode === "dispatch" ? "auto" : mode;
}

function sortConversations(conversations: Conversation[]): Conversation[] {
  return [...conversations].sort((left, right) =>
    right.updatedAt.localeCompare(left.updatedAt),
  );
}

function createConversationRecord(
  existing: Conversation | null,
  request: ChatRequest,
  newMessages: ChatMessage[],
): Conversation {
  const normalizedMode = normalizeChatMode(request.mode);
  const finalMessages = [...request.conversation, ...newMessages];
  const firstUserMessage = finalMessages.find((message) => message.role === "user");
  const lastMessage = finalMessages.at(-1) ?? null;
  const createdAt = existing?.createdAt ?? firstUserMessage?.createdAt ?? new Date().toISOString();

  return {
    id: existing?.id ?? request.conversationId ?? createId("conv"),
    title: summarizeText(firstUserMessage?.content ?? "New chat", 48),
    mode: normalizedMode,
    createdAt,
    updatedAt: new Date().toISOString(),
    lastMessageAt: lastMessage?.createdAt ?? null,
    preview: summarizeText(lastMessage?.content ?? firstUserMessage?.content ?? ""),
    messageCount: finalMessages.length,
    messages: finalMessages,
  };
}

type ExecutionRole = Exclude<Role, "dispatch">;

function resolveSpeakingRole(role: Role | null): Role {
  return role === "dispatch" || role === null ? "coordinator" : role;
}

function roleLead(role: Role): string {
  switch (role) {
    case "dispatch":
      return "Routing analysis";
    case "coordinator":
      return "Operator-facing response";
    case "advisor":
      return "Execution plan";
    case "director":
      return "Implementation direction";
    case "inspector":
      return "Audit pass";
    case "ops":
      return "Polish pass";
  }
}

function createBlocks(
  role: Role,
  mode: ChatMode,
  content: string,
  providerName: string | null,
  modelId: string | null,
  executionSource: "live" | "fallback",
  note: string,
): UiBlock[] {
  const trimmed = content.trim();
  return [
    {
      type: "summary",
      title: roleLead(role),
      body:
        executionSource === "live"
          ? `This ${role} response was generated by a connected provider in ${mode === "auto" ? "Auto" : "direct"} mode.`
          : `This ${role} response is using EMBER's local fallback path because no live provider execution was available.`,
    },
    {
      type: "checklist",
      title: "Next actions",
      items: [
        {
          label: trimmed
            ? `Handle request: ${trimmed.slice(0, 72)}${trimmed.length > 72 ? "..." : ""}`
            : "Handle the incoming request",
          state: "active",
        },
        {
          label: providerName
            ? `Use assigned provider ${providerName}`
            : "No provider assigned yet for this role",
          state: providerName ? "complete" : "pending",
        },
        {
          label: modelId ? `Use model ${modelId}` : "Model selection still unassigned",
          state: modelId ? "complete" : "pending",
        },
        {
          label:
            executionSource === "live"
              ? "Provider execution is active"
              : "Execution fell back to the local scaffold",
          state: executionSource === "live" ? "complete" : "active",
        },
      ],
    },
    {
      type: "stat-grid",
      title: "Execution metadata",
      stats: [
        { label: "Role", value: role },
        { label: "Mode", value: mode === "auto" ? "Auto" : "Direct" },
        { label: "Provider", value: providerName ?? "Unassigned" },
        { label: "Model", value: modelId ?? "Unassigned" },
        { label: "Source", value: executionSource === "live" ? "Live provider" : "Fallback" },
      ],
    },
    {
      type: "note",
      tone: executionSource === "live" ? "success" : "warning",
      body: note,
    },
  ];
}

function createStatusError(statusCode: number, message: string): Error & { statusCode: number } {
  const error = new Error(message) as Error & { statusCode: number };
  error.statusCode = statusCode;
  return error;
}

function resolveBrowserSessionKey(request: ChatRequest): string {
  return (
    request.conversation.find((message) => message.role === "user")?.id ??
    request.conversationId ??
    createId("browser")
  );
}

interface ExecutionContext {
  mode: ChatMode;
  settings: Awaited<ReturnType<typeof readSettings>>;
  providers: Provider[];
  secrets: Awaited<ReturnType<typeof readProviderSecrets>>;
  assignmentMap: Map<Role, RoleAssignment>;
  routeDecision: AutoRouteDecision | null;
  routedTo: Role | null;
  activeRole: Role;
  promptStack: ReturnType<typeof getPromptStack>;
  tools: ReturnType<typeof getToolsForRole>;
  assignment: RoleAssignment | undefined;
  provider: Provider | null;
  responseModelId: string | null;
  routeNote: string | null;
  browserSessionKey: string;
}

function sendStreamEvent(
  emit: ((event: ChatStreamEvent) => void) | undefined,
  event: ChatStreamEvent,
) {
  emit?.(event);
}

function buildReplyMessage(
  context: ExecutionContext,
  request: ChatRequest,
  responseContent: string,
  responseThinking: string | null,
  responseModelId: string | null,
  executionNote: string,
): ChatMessage {
  return {
    id: createId("msg"),
    role: "assistant",
    authorRole: context.activeRole,
    mode: context.mode,
    content: responseContent,
    thinking: responseThinking,
    createdAt: new Date().toISOString(),
    providerId: context.provider?.id ?? null,
    providerName: context.provider?.name ?? null,
    modelId: responseModelId,
    routedTo: context.routedTo,
    blocks: createBlocks(
      context.activeRole,
      context.mode,
      request.content,
      context.provider?.name ?? null,
      responseModelId,
      "live",
      executionNote,
    ),
  };
}

const MAX_AGENT_LOOP = 16;
const MAX_ROLE_VISITS = 5;
const DISPATCH_TIMEOUT_MS = 10_000;

function buildHandoffContext(source: ExecutionContext, targetRole: ExecutionRole): ExecutionContext {
  const assignment = source.assignmentMap.get(targetRole);
  const provider = source.providers.find((p) => p.id === assignment?.providerId) ?? null;
  const responseModelId =
    assignment?.modelId ?? provider?.config.defaultModelId ?? provider?.availableModels[0] ?? null;
  const tools = provider && !provider.capabilities.canUseTools ? [] : getToolsForRole(targetRole);
  const promptStack = getPromptStack(source.settings, targetRole);
  promptStack.tools = getToolSystemPrompt(tools);
  return {
    ...source,
    activeRole: targetRole,
    promptStack,
    tools,
    assignment,
    provider,
    responseModelId,
    routedTo: targetRole,
    routeNote: `${source.activeRole} chained to ${targetRole}.`,
  };
}

async function resolveAutoRouteDecision(
  request: ChatRequest,
  settings: ExecutionContext["settings"],
  providers: Provider[],
  assignmentMap: Map<Role, RoleAssignment>,
  secrets: ExecutionContext["secrets"],
): Promise<AutoRouteDecision> {
  const policy = routeAutoRequestPolicy(request);
  if (!policy.shouldQueryDispatch) {
    return policy.decision;
  }

  const routerAssignment = assignmentMap.get("dispatch");
  const routerProvider =
    providers.find((candidate) => candidate.id === routerAssignment?.providerId) ?? null;

  if (!routerProvider || routerProvider.status !== "connected" || !providerCanChat(routerProvider)) {
    const reason = !routerProvider
      ? "Dispatch provider is not assigned."
      : routerProvider.status !== "connected"
        ? `Dispatch provider ${routerProvider.name} is ${routerProvider.status}.`
        : `Dispatch provider ${routerProvider.name} cannot execute chat requests.`;
    return {
      ...policy.decision,
      source: "policy-fallback",
      reason: `${reason} Using the policy fallback.`,
    };
  }

  try {
    console.log(`[dispatch] calling ${routerProvider.name} (${routerAssignment?.modelId ?? "default model"})`);
    const routerExecution = await Promise.race([
      executeProviderChat(routerProvider, secrets, {
        modelId: routerAssignment?.modelId ?? null,
        promptStack: getPromptStack(settings, "dispatch"),
        role: "dispatch",
        conversation: [],
        content: buildDispatchInput(request),
        purpose: "route",
      }),
      new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error(`Dispatch timed out after ${DISPATCH_TIMEOUT_MS}ms.`));
        }, DISPATCH_TIMEOUT_MS).unref();
      }),
    ]);
    console.log(`[dispatch] raw response: "${routerExecution.content}"`);
    const decision = resolveDispatchDecision(routerExecution.content, policy.decision);
    console.log(
      `[dispatch] parsed role: ${decision.role} (source: ${decision.source}, confidence: ${decision.confidence.toFixed(2)})`,
    );
    return decision;
  } catch (error) {
    console.warn(
      `[dispatch] failed, using policy fallback. reason: ${error instanceof Error ? error.message : String(error)}`,
    );
    return {
      ...policy.decision,
      source: "policy-fallback",
      reason: `Dispatch failed, so the policy fallback kept ${policy.decision.role}.`,
    };
  }
}

async function prepareExecution(request: ChatRequest): Promise<ExecutionContext> {
  const mode = normalizeChatMode(request.mode);
  const [settings, providers, assignments, secrets] = await Promise.all([
    readSettings(),
    readProviders(),
    readRoleAssignments(),
    readProviderSecrets(),
  ]);

  const assignmentMap = new Map<Role, RoleAssignment>(
    assignments.map((assignment) => [assignment.role, assignment]),
  );

  setToolConfig({ sudoPassword: settings.sudoPassword ?? "" });

  const routeDecision =
    mode === "auto"
      ? await resolveAutoRouteDecision(request, settings, providers, assignmentMap, secrets)
      : null;
  const routedTo = mode === "auto" ? resolveSpeakingRole(routeDecision?.role ?? null) : null;
  const activeRole = mode === "auto" ? routedTo ?? "coordinator" : resolveSpeakingRole(mode);
  const assignment = assignmentMap.get(activeRole);
  const provider = providers.find((candidate) => candidate.id === assignment?.providerId) ?? null;
  const tools = provider && !provider.capabilities.canUseTools ? [] : getToolsForRole(activeRole);
  const promptStack = getPromptStack(settings, activeRole);
  promptStack.tools = getToolSystemPrompt(tools);
  const responseModelId =
    assignment?.modelId ?? provider?.config.defaultModelId ?? provider?.availableModels[0] ?? null;
  const routeNote = routeDecision
    ? `Auto routed to ${routeDecision.role} via ${formatRouteSource(routeDecision.source)}.`
    : null;

  return {
    mode,
    settings,
    providers,
    secrets,
    assignmentMap,
    routeDecision,
    routedTo,
    activeRole,
    promptStack,
    tools,
    assignment,
    provider,
    responseModelId,
    routeNote,
    browserSessionKey: resolveBrowserSessionKey(request),
  };
}

function resolveExecutionGuard(context: ExecutionContext): never {
  const { provider, routeNote } = context;
  let executionNote = provider
    ? `Assigned provider ${provider.name} is not ready for live execution yet.`
    : "No provider is assigned to this role yet.";

  if (provider && !providerCanChat(provider)) {
    executionNote =
      "This provider can be connected and rechecked, but role execution is not wired for this connector type yet.";
  } else if (provider && provider.status !== "connected") {
    executionNote = `Assigned provider ${provider.name} is currently ${provider.status}. Recheck the connection before using live execution.`;
  }

  if (routeNote) {
    executionNote = `${routeNote} ${executionNote}`;
  }

  throw createStatusError(409, executionNote);
}

async function persistConversationFromResult(
  request: ChatRequest,
  result: ChatExecutionResult,
) {
  const conversations = await readConversations();
  const existing = request.conversationId
    ? conversations.find((item) => item.id === request.conversationId) ?? null
    : null;
  const conversation = createConversationRecord(existing, request, result.messages);
  const remaining = conversations.filter((item) => item.id !== conversation.id);
  const nextConversations = sortConversations([conversation, ...remaining]);

  await writeConversations(nextConversations);

  return conversation;
}

async function buildExecution(
  request: ChatRequest,
): Promise<ChatExecutionResult> {
  const context = await prepareExecution(request);
  const provider = context.provider;
  if (!provider || provider.status !== "connected" || !providerCanChat(provider)) {
    resolveExecutionGuard(context);
  }

  if (requestHasImageAttachments(request) && !provider.capabilities.canUseImages) {
    throw createStatusError(
      409,
      `${provider.name} does not accept image inputs. Switch to an image-capable provider or remove the image.`,
    );
  }

  const messages: ChatMessage[] = [];
  const visitCounts = new Map<string, number>();
  let currentCtx = context;
  let currentConversation = request.conversation;
  let currentContent = request.content;

  for (let iteration = 0; iteration < MAX_AGENT_LOOP; iteration++) {
    const iterProvider = currentCtx.provider;
    if (!iterProvider || iterProvider.status !== "connected" || !providerCanChat(iterProvider)) {
      if (iteration === 0) resolveExecutionGuard(currentCtx);
      console.warn(`[loop] no usable provider for ${currentCtx.activeRole}, stopping`);
      break;
    }

    const handler = createToolHandler({ browserSessionKey: currentCtx.browserSessionKey });
    let iterContent: string;
    let iterThinking: string | null;
    let iterModelId: string | null;

    try {
      const iterExecution = await executeProviderChat(iterProvider, currentCtx.secrets, {
        modelId: currentCtx.assignment?.modelId ?? null,
        promptStack: currentCtx.promptStack,
        role: currentCtx.activeRole,
        conversation: currentConversation,
        content: currentContent,
        tools: currentCtx.tools,
        onToolCall: handler.onToolCall,
      });
      iterContent = iterExecution.content;
      iterThinking = iterExecution.thinking ?? null;
      iterModelId = iterExecution.modelId;
    } catch (error) {
      const note = `${currentCtx.routeNote ? `${currentCtx.routeNote} ` : ""}Live provider execution failed: ${
        error instanceof Error ? error.message : "Unknown error."
      }`;
      if (iteration === 0) throw createStatusError(502, note);
      console.warn(`[loop] ${currentCtx.activeRole} failed: ${note}`);
      break;
    }

    const iterNote = `${currentCtx.routeNote ?? ""} Live response via ${iterProvider.name}.`.trim();
    const iterMsg = buildReplyMessage(currentCtx, request, iterContent, iterThinking, iterModelId, iterNote);
    messages.push(iterMsg);

    const handoff = handler.getPendingHandoff();
    if (!handoff) break;

    const visits = (visitCounts.get(handoff.role) ?? 0) + 1;
    if (visits > MAX_ROLE_VISITS) {
      console.warn(`[loop] ${handoff.role} hit visit limit (${MAX_ROLE_VISITS}), stopping`);
      break;
    }
    visitCounts.set(handoff.role, visits);
    console.log(`[loop] ${currentCtx.activeRole} → handoff: ${handoff.role} (visit ${visits})`);

    currentConversation = [...currentConversation, iterMsg];
    currentContent = handoff.message;
    currentCtx = buildHandoffContext(currentCtx, handoff.role as ExecutionRole);
  }

  const lastMessage = messages.at(-1)!;
  return {
    messages,
    activeRole: (lastMessage.authorRole as Role) ?? context.activeRole,
    providerId: lastMessage.providerId ?? provider.id,
    providerName: lastMessage.providerName ?? provider.name,
    modelId: lastMessage.modelId ?? context.responseModelId,
    promptStack: context.promptStack,
    routedTo: context.routedTo,
    conversationId: request.conversationId ?? null,
  };
}

const app = Fastify({
  bodyLimit: 12 * 1024 * 1024,
  logger: false,
});

await ensureDataFiles();

await app.register(cors, {
  origin: true,
});

app.get("/health", async () => {
  const runtime = await readRuntime();
  return {
    status: "ok",
    runtime,
    now: new Date().toISOString(),
  };
});

app.get("/api/runtime", async () => {
  const [runtime, settings] = await Promise.all([readRuntime(), readSettings()]);
  return {
    runtime,
    settings,
  };
});

app.get("/api/connector-types", async () => {
  return {
    items: await readConnectorTypes(),
  };
});

app.get("/api/connector-models", async () => {
  return {
    items: getConnectorModelCatalog() as Partial<Record<ConnectorTypeId, string[]>>,
  };
});

app.get("/api/conversations", async () => {
  const conversations = await readConversations();
  return {
    items: sortConversations(conversations).map(toConversationSummary),
  };
});

app.get("/api/conversations/:id", async (request, reply) => {
  const id = (request.params as { id: string }).id;
  const conversations = await readConversations();
  const conversation = conversations.find((item) => item.id === id);

  if (!conversation) {
    reply.code(404);
    return { error: "Conversation not found." };
  }

  return {
    item: conversation,
  };
});

app.patch("/api/conversations/:id", async (request, reply) => {
  const id = (request.params as { id: string }).id;
  const body = request.body as { title?: string };
  const conversations = await readConversations();
  const existing = conversations.find((item) => item.id === id);

  if (!existing) {
    reply.code(404);
    return { error: "Conversation not found." };
  }

  const nextTitle = summarizeText(body.title ?? existing.title, 48);
  const updated = conversations.map((item) =>
    item.id === id
      ? {
          ...item,
          title: nextTitle,
          updatedAt: new Date().toISOString(),
        }
      : item,
  );

  await writeConversations(sortConversations(updated));

  return {
    item: updated.find((item) => item.id === id),
  };
});

app.delete("/api/conversations/:id", async (request, reply) => {
  const id = (request.params as { id: string }).id;
  const conversations = await readConversations();
  const remaining = conversations.filter((item) => item.id !== id);

  if (remaining.length === conversations.length) {
    reply.code(404);
    return { error: "Conversation not found." };
  }

  await writeConversations(sortConversations(remaining));
  return { ok: true };
});

app.get("/api/providers", async () => {
  const [providers, connectorTypes] = await Promise.all([
    readProviders(),
    readConnectorTypes(),
  ]);

  return {
    items: providers.map((provider) => ({
      ...provider,
      connectorType:
        connectorTypes.find((item) => item.id === provider.typeId) ?? null,
    })),
  };
});

app.post("/api/providers", async (request, reply) => {
  const body = request.body as {
    name?: string;
    typeId?: Provider["typeId"];
    config?: Record<string, string>;
    secrets?: Record<string, string>;
  };

  if (!body?.name || !body?.typeId) {
    reply.code(400);
    return { error: "name and typeId are required." };
  }

  const [providers, secrets] = await Promise.all([
    readProviders(),
    readProviderSecrets(),
  ]);

  const provider: Provider = {
    id: createId("provider"),
    name: body.name.trim(),
    typeId: body.typeId,
    status: "idle",
    config: body.config ?? {},
    availableModels: [],
    capabilities: getProviderCapabilities(body.typeId),
    lastError: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  providers.unshift(provider);
  await writeProviders(providers);

  if (body.secrets && Object.keys(body.secrets).length > 0) {
    secrets[provider.id] = body.secrets;
    await writeProviderSecrets(secrets);
  }

  reply.code(201);
  return { item: provider };
});

app.put("/api/providers/:id", async (request, reply) => {
  const id = (request.params as { id: string }).id;
  const body = request.body as {
    name?: string;
    config?: Record<string, string>;
    secrets?: Record<string, string>;
    clearSecrets?: string[];
  };

  const [providers, secrets] = await Promise.all([
    readProviders(),
    readProviderSecrets(),
  ]);
  const provider = providers.find((candidate) => candidate.id === id);

  if (!provider) {
    reply.code(404);
    return { error: "Provider not found." };
  }

  if (typeof body?.name === "string" && body.name.trim().length === 0) {
    reply.code(400);
    return { error: "Provider name cannot be empty." };
  }

  const nextConfig = {
    ...provider.config,
    ...sanitizeRecord(body?.config),
  };

  if (body?.config) {
    for (const [key, value] of Object.entries(body.config)) {
      if (typeof value === "string" && value.trim().length === 0) {
        delete nextConfig[key];
      }
    }
  }

  const currentSecrets = { ...(secrets[id] ?? {}) };
  if (body?.clearSecrets?.length) {
    for (const key of body.clearSecrets) {
      delete currentSecrets[key];
    }
  }

  Object.assign(currentSecrets, sanitizeRecord(body?.secrets));
  if (Object.keys(currentSecrets).length === 0) {
    delete secrets[id];
  } else {
    secrets[id] = currentSecrets;
  }

  const updated = providers.map((candidate) =>
    candidate.id === id
      ? {
          ...candidate,
          name: body?.name?.trim() || candidate.name,
          config: nextConfig,
          updatedAt: new Date().toISOString(),
        }
      : candidate,
  );

  await Promise.all([
    writeProviders(updated),
    writeProviderSecrets(secrets),
  ]);

  return { item: updated.find((candidate) => candidate.id === id) };
});

app.post("/api/providers/:id/connect", async (request, reply) => {
  const id = (request.params as { id: string }).id;
  const [providers, secrets] = await Promise.all([
    readProviders(),
    readProviderSecrets(),
  ]);
  const provider = providers.find((candidate) => candidate.id === id);

  if (!provider) {
    reply.code(404);
    return { error: "Provider not found." };
  }

  const existingStatus = await recheckProvider(provider, secrets);
  const result =
    existingStatus.status === "connected"
      ? existingStatus
      : provider.capabilities.requiresBrowserAuth
        ? launchProviderConnect(provider)
        : existingStatus;
  const updated = providers.map((candidate) =>
    candidate.id === id
      ? {
          ...candidate,
          status: result.status,
          availableModels: result.availableModels,
          lastError: result.lastError,
          updatedAt: new Date().toISOString(),
        }
      : candidate,
  );

  await writeProviders(updated);
  return { item: updated.find((candidate) => candidate.id === id) };
});

app.post("/api/providers/:id/reconnect", async (request, reply) => {
  const id = (request.params as { id: string }).id;
  const [providers, secrets] = await Promise.all([
    readProviders(),
    readProviderSecrets(),
  ]);
  const provider = providers.find((candidate) => candidate.id === id);

  if (!provider) {
    reply.code(404);
    return { error: "Provider not found." };
  }

  const result = provider.capabilities.requiresBrowserAuth
    ? launchProviderConnect(provider)
    : await recheckProvider(provider, secrets);

  const updated = providers.map((candidate) =>
    candidate.id === id
      ? {
          ...candidate,
          status: result.status,
          availableModels: result.availableModels,
          lastError: result.lastError,
          updatedAt: new Date().toISOString(),
        }
      : candidate,
  );

  await writeProviders(updated);
  return { item: updated.find((candidate) => candidate.id === id) };
});

app.post("/api/providers/:id/recheck", async (request, reply) => {
  const id = (request.params as { id: string }).id;
  const [providers, secrets] = await Promise.all([
    readProviders(),
    readProviderSecrets(),
  ]);
  const provider = providers.find((candidate) => candidate.id === id);

  if (!provider) {
    reply.code(404);
    return { error: "Provider not found." };
  }

  const result = await recheckProvider(provider, secrets);
  const updated = providers.map((candidate) =>
    candidate.id === id
      ? {
          ...candidate,
          status: result.status,
          availableModels: result.availableModels,
          lastError: result.lastError,
          updatedAt: new Date().toISOString(),
        }
      : candidate,
  );

  await writeProviders(updated);
  return { item: updated.find((candidate) => candidate.id === id) };
});

app.delete("/api/providers/:id", async (request, reply) => {
  const id = (request.params as { id: string }).id;
  const [providers, secrets, assignments] = await Promise.all([
    readProviders(),
    readProviderSecrets(),
    readRoleAssignments(),
  ]);

  const remainingProviders = providers.filter((provider) => provider.id !== id);
  if (remainingProviders.length === providers.length) {
    reply.code(404);
    return { error: "Provider not found." };
  }

  delete secrets[id];

  const sanitizedAssignments = assignments.map((assignment) =>
    assignment.providerId === id
      ? {
          ...assignment,
          providerId: null,
          modelId: null,
        }
      : assignment,
  );

  await Promise.all([
    writeProviders(remainingProviders),
    writeProviderSecrets(secrets),
    writeRoleAssignments(sanitizedAssignments),
  ]);

  return { ok: true };
});

app.get("/api/roles", async () => {
  const [assignments, providers] = await Promise.all([
    readRoleAssignments(),
    readProviders(),
  ]);
  return {
    items: assignments.map((assignment) => ({
      ...assignment,
      provider: providers.find((provider) => provider.id === assignment.providerId) ?? null,
    })),
    providers,
  };
});

app.put("/api/roles", async (request, reply) => {
  const body = request.body as { items?: RoleAssignment[] };
  if (!body?.items) {
    reply.code(400);
    return { error: "items are required." };
  }

  await writeRoleAssignments(body.items);
  return { items: body.items };
});

app.get("/api/settings", async () => {
  return {
    item: await readSettings(),
  };
});

app.put("/api/settings", async (request, reply) => {
  const body = request.body as { item?: Awaited<ReturnType<typeof readSettings>> };
  if (!body?.item) {
    reply.code(400);
    return { error: "item is required." };
  }

  await writeSettings(body.item);
  return { item: body.item };
});

app.get("/api/prompts/:role", async (request, reply) => {
  const role = (request.params as { role: Role }).role;
  const settings = await readSettings();
  if (!["dispatch", "coordinator", "advisor", "director", "inspector", "ops"].includes(role)) {
    reply.code(400);
    return { error: "Unknown role." };
  }

  return {
    item: getPromptStack(settings, role),
  };
});

app.post("/api/chat", async (request) => {
  const body = request.body as ChatRequest;
  const result = await buildExecution(body);
  const conversation = await persistConversationFromResult(body, result);

  return {
    ...result,
    conversationId: conversation.id,
    conversation: toConversationSummary(conversation),
  };
});

app.post("/api/chat/stream", async (request, reply) => {
  const body = request.body as ChatRequest;

  reply.hijack();
  reply.raw.writeHead(200, {
    "content-type": "application/x-ndjson; charset=utf-8",
    "cache-control": "no-cache, no-transform",
    connection: "keep-alive",
    "x-accel-buffering": "no",
  });
  reply.raw.flushHeaders?.();

  // Disable Nagle's algorithm so each event flushes to the client immediately.
  (reply.raw.socket as import("node:net").Socket | null)?.setNoDelay(true);

  const send = (event: ChatStreamEvent) => {
    reply.raw.write(`${JSON.stringify(event)}\n`);
    (reply.raw as typeof reply.raw & { flush?: () => void }).flush?.();
  };

  // Send an immediate heartbeat so the client knows the server is alive
  // before the (potentially slow) routing/dispatch LLM call begins.
  const mode = normalizeChatMode(body.mode);
  send({
    type: "status",
    phase: "routing",
    message: mode === "auto" ? "Evaluating route..." : "Connecting to provider...",
    role: null,
    providerName: null,
    modelId: null,
  });

  try {
    const context = await prepareExecution(body);

    if (context.routeDecision) {
      sendStreamEvent(send, {
        type: "status",
        phase: "routing",
        message: `Auto routed to ${context.routeDecision.role} via ${formatRouteSource(context.routeDecision.source)}.`,
        role: context.routeDecision.role,
        providerName: context.provider?.name ?? null,
        modelId: context.responseModelId,
      });
    }

    const provider = context.provider;

    if (requestHasImageAttachments(body) && provider && !provider.capabilities.canUseImages) {
      throw createStatusError(
        409,
        `${provider.name} does not accept image inputs. Switch to an image-capable provider or remove the image.`,
      );
    }

    const resultMessages: ChatMessage[] = [];
    const streamVisitCounts = new Map<string, number>();
    let streamCtx = context;
    let streamConversation = [...body.conversation];
    let streamContent = body.content;

    for (let iteration = 0; iteration < MAX_AGENT_LOOP; iteration++) {
      const iterProvider = streamCtx.provider;
      if (!iterProvider || iterProvider.status !== "connected" || !providerCanChat(iterProvider)) {
        if (iteration === 0) resolveExecutionGuard(streamCtx);
        console.warn(`[loop] no usable provider for ${streamCtx.activeRole}, stopping`);
        break;
      }

      if (iteration === 0) {
        sendStreamEvent(send, {
          type: "status",
          phase: "provider",
          message: `Using ${iterProvider.name}${streamCtx.responseModelId ? ` with ${streamCtx.responseModelId}` : ""}.`,
          role: streamCtx.activeRole,
          providerName: iterProvider.name,
          modelId: streamCtx.responseModelId,
        });
      } else {
        sendStreamEvent(send, {
          type: "status",
          phase: "routing",
          message: `Handing off to ${streamCtx.activeRole}...`,
          role: streamCtx.activeRole,
          providerName: iterProvider.name,
          modelId: streamCtx.responseModelId,
        });
      }

      const handler = createToolHandler({ browserSessionKey: streamCtx.browserSessionKey });
      let iterThinking = "";
      let iterContent = "";

      try {
        const iterExecution = await streamProviderChat(
          iterProvider,
          context.secrets,
          {
            modelId: streamCtx.assignment?.modelId ?? null,
            promptStack: streamCtx.promptStack,
            role: streamCtx.activeRole,
            conversation: streamConversation,
            content: streamContent,
            tools: streamCtx.tools,
            onToolCall: handler.onToolCall,
          },
          {
            onStatus(message) {
              sendStreamEvent(send, {
                type: "status",
                phase: "streaming",
                message,
                role: streamCtx.activeRole,
                providerName: iterProvider.name,
                modelId: streamCtx.responseModelId,
              });
            },
            onThinking(text) {
              iterThinking += text;
              sendStreamEvent(send, { type: "thinking", text });
            },
            onContent(text) {
              iterContent += text;
              sendStreamEvent(send, { type: "content", text });
            },
          },
        );

        const iterNote = `${streamCtx.routeNote ?? ""} Live response via ${iterProvider.name}.`.trim();
        const iterMsg = buildReplyMessage(
          streamCtx, body, iterExecution.content, iterExecution.thinking ?? null, iterExecution.modelId, iterNote,
        );
        resultMessages.push(iterMsg);

        const handoff = handler.getPendingHandoff();
        if (!handoff) break;

        const visits = (streamVisitCounts.get(handoff.role) ?? 0) + 1;
        if (visits > MAX_ROLE_VISITS) {
          console.warn(`[loop] ${handoff.role} hit visit limit (${MAX_ROLE_VISITS}), stopping`);
          break;
        }
        streamVisitCounts.set(handoff.role, visits);
        console.log(`[loop] ${streamCtx.activeRole} → handoff: ${handoff.role} (visit ${visits})`);

        streamConversation = [...streamConversation, iterMsg];
        streamContent = handoff.message;
        streamCtx = buildHandoffContext(streamCtx, handoff.role as ExecutionRole);
      } catch (chainError) {
        if (iteration === 0) throw chainError;
        console.warn(`[loop] ${streamCtx.activeRole} failed: ${chainError instanceof Error ? chainError.message : String(chainError)}`);
        break;
      }
    }

    const lastResultMessage = resultMessages.at(-1)!;
    const result: ChatExecutionResult = {
      messages: resultMessages,
      activeRole: (lastResultMessage.authorRole as Role) ?? context.activeRole,
      providerId: lastResultMessage.providerId ?? provider?.id ?? null,
      providerName: lastResultMessage.providerName ?? provider?.name ?? null,
      modelId: lastResultMessage.modelId ?? context.responseModelId,
      promptStack: context.promptStack,
      routedTo: context.routedTo,
      conversationId: body.conversationId ?? null,
    };

    sendStreamEvent(send, {
      type: "status",
      phase: "saving",
      message: "Saving conversation...",
      role: context.activeRole,
      providerName: provider?.name ?? null,
      modelId: context.responseModelId,
    });

    const conversation = await persistConversationFromResult(body, result);
    sendStreamEvent(send, {
      type: "complete",
      message: lastResultMessage,
      conversationId: conversation.id,
      conversation: toConversationSummary(conversation),
    });
  } catch (error) {
    sendStreamEvent(send, {
      type: "error",
      message: error instanceof Error ? error.message : "Chat request failed.",
      statusCode:
        error && typeof error === "object" && "statusCode" in error
          ? Number((error as { statusCode?: unknown }).statusCode) || undefined
          : undefined,
    });
  } finally {
    reply.raw.end();
  }

  return reply;
});

app.listen({ host, port }).catch((error) => {
  console.error(error);
  process.exit(1);
});
